// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {service} from '../models';
import {core} from '../models';

export function ConvertBsToUsd(arg1:number,arg2:number):Promise<number>;

export function ConvertUsdToBs(arg1:number,arg2:number):Promise<number>;

export function CreateCategory(arg1:string,arg2:string):Promise<number>;

export function CreateTransaction(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:any,arg9:string):Promise<number>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetCurrentExchangeRates():Promise<main.ExchangeRateResult>;

export function GetLastExchangeRates():Promise<main.ExchangeRateResult>;

export function GetMonthlySummary(arg1:string,arg2:string):Promise<service.MonthlySummary>;

export function GetTransaction(arg1:number):Promise<core.Transaction>;

export function GetYearlySummary(arg1:string):Promise<service.MonthlySummary>;

export function Greet(arg1:string):Promise<string>;

export function ListCategories(arg1:string):Promise<Array<core.Category>>;

export function ListTransactions(arg1:string,arg2:string,arg3:string):Promise<Array<core.Transaction>>;

export function UpdateCategory(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateTransaction(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:any,arg10:string):Promise<void>;
