// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertBsToUsd(arg1, arg2) {
  return window['go']['main']['App']['ConvertBsToUsd'](arg1, arg2);
}

export function ConvertUsdToBs(arg1, arg2) {
  return window['go']['main']['App']['ConvertUsdToBs'](arg1, arg2);
}

export function CreateCategory(arg1, arg2) {
  return window['go']['main']['App']['CreateCategory'](arg1, arg2);
}

export function CreateTransaction(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateTransaction'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function GetCurrentExchangeRates() {
  return window['go']['main']['App']['GetCurrentExchangeRates']();
}

export function GetLastExchangeRates() {
  return window['go']['main']['App']['GetLastExchangeRates']();
}

export function GetMonthlySummary(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlySummary'](arg1, arg2);
}

export function GetTransaction(arg1) {
  return window['go']['main']['App']['GetTransaction'](arg1);
}

export function GetYearlySummary(arg1) {
  return window['go']['main']['App']['GetYearlySummary'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListCategories(arg1) {
  return window['go']['main']['App']['ListCategories'](arg1);
}

export function ListTransactions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTransactions'](arg1, arg2, arg3);
}

export function UpdateCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2, arg3);
}

export function UpdateTransaction(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['UpdateTransaction'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}
